const rootNode = document.getRootNode();
const htmlElementNode = rootNode.childNodes[0];
// console.log(htmlElementNode.childNodes);
const headElementNode = htmlElementNode.childNodes[0];
const textNode = htmlElementNode.childNodes[1];
const bodyElementNode = htmlElementNode.childNodes[2];
// console.log(headElementNode.nextElementSibling);
console.log(headElementNode.childNodes);
console.log(textNode);
console.log(bodyElementNode);
const mainHeading = document.querySelector("h1");
const mainHeadingParent = mainHeading.parentElement;
mainHeadingParent.style.backgroundColor = "red";
const mainHeadingGrandParent = mainHeadingParent.parentElement;
mainHeadingGrandParent.style.backgroundColor = "black";
const head = document.querySelector("head");
const title = head.querySelector("title");
console.log(title);
const container = document.querySelector(".container");
console.log(container.children);
